src/Entity/FicheFrais.php
<?php

namespace App\Entity;

use App\Repository\FicheFraisRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FicheFraisRepository::class)]
#[UniqueEntity(
    fields: ['user', 'mois'],
    errorPath: 'mois',
    message: 'Une fiche frais existe déjà pour le mois.',
)]
class FicheFrais
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'ficheFrais')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 10)]
    private ?string $mois = null;

    #[ORM\Column]
    private ?int $nbJustificatifs = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $montantValide = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateModif = null;

    #[ORM\ManyToOne(inversedBy: 'ficheFrais', fetch: 'EAGER')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Etat $etat = null;

    #[ORM\OneToMany(mappedBy: 'fichefrais', targetEntity: LigneFraisForfait::class, orphanRemoval: true, fetch: 'EAGER', cascade: ['persist', 'remove'])]
    private Collection $ligneFraisForfaits;

    #[ORM\OneToMany(mappedBy: 'fichefrais', targetEntity: LigneFraisHorsForfait::class, orphanRemoval: true, fetch: 'EAGER', cascade: ['persist', 'remove'])]
    private Collection $ligneFraisHorsForfaits;

    public function __construct()
    {
        $this->ligneFraisForfaits = new ArrayCollection();
        $this->ligneFraisHorsForfaits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMois(): ?string
    {
        return $this->mois;
    }

    public function __toString(): string
    {
        return $this->getMois();
    }

    public function getMoisFormated(): ?\DateTimeImmutable
    {
        return DateTimeImmutable::createFromFormat('Ym', $this->getMois());
    }

    public function setMois(string $mois): self
    {
        $this->mois = $mois;

        return $this;
    }

    public function getNbJustificatifs(): ?int
    {
        return $this->nbJustificatifs;
    }

    public function setNbJustificatifs(int $nbJustificatifs): self
    {
        $this->nbJustificatifs = $nbJustificatifs;

        return $this;
    }

    public function getMontantValide(): ?string
    {
        return $this->montantValide;
    }

    public function setMontantValide(string $montantValide): self
    {
        $this->montantValide = $montantValide;

        return $this;
    }

    public function getDateModif(): ?\DateTimeInterface
    {
        return $this->dateModif;
    }

    public function setDateModif(?\DateTimeInterface $dateModif): self
    {
        $this->dateModif = $dateModif;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, LigneFraisForfait>
     */
    public function getLigneFraisForfaits(): Collection
    {
        return $this->ligneFraisForfaits;
    }

    public function addLigneFraisForfait(LigneFraisForfait $ligneFraisForfait): self
    {
        if (!$this->ligneFraisForfaits->contains($ligneFraisForfait)) {
            $this->ligneFraisForfaits->add($ligneFraisForfait);
            $ligneFraisForfait->setFichefrais($this);
        }

        return $this;
    }

    public function removeLigneFraisForfait(LigneFraisForfait $ligneFraisForfait): self
    {
        if ($this->ligneFraisForfaits->removeElement($ligneFraisForfait)) {
            // set the owning side to null (unless already changed)
            if ($ligneFraisForfait->getFichefrais() === $this) {
                $ligneFraisForfait->setFichefrais(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LigneFraisHorsForfait>
     */
    public function getLigneFraisHorsForfaits(): Collection
    {
        return $this->ligneFraisHorsForfaits;
    }

    public function addLigneFraisHorsForfait(LigneFraisHorsForfait $ligneFraisHorsForfait): self
    {
        if (!$this->ligneFraisHorsForfaits->contains($ligneFraisHorsForfait)) {
            $this->ligneFraisHorsForfaits->add($ligneFraisHorsForfait);
            $ligneFraisHorsForfait->setFichefrais($this);
        }

        return $this;
    }

    public function removeLigneFraisHorsForfait(LigneFraisHorsForfait $ligneFraisHorsForfait): self
    {
        if ($this->ligneFraisHorsForfaits->removeElement($ligneFraisHorsForfait)) {
            // set the owning side to null (unless already changed)
            if ($ligneFraisHorsForfait->getFichefrais() === $this) {
                $ligneFraisHorsForfait->setFichefrais(null);
            }
        }

        return $this;
    }

    public function montantTotalFrais()
    {
        $totalFraisForfait = 0;
        $totalFraisHorsForfait = 0;

        foreach ($this->getLigneFraisForfaits() as $lff)
        {
            $totalFraisForfait += $lff->getQuantite() * $lff->getFraisforfait()->getMontant();
        }
        foreach ($this->getLigneFraisHorsForfaits() as $lfhf)
        {
            $totalFraisHorsForfait += $lfhf->getMontant();
        }

        return $totalFraisForfait + $totalFraisHorsForfait;
    }
}

src/Controller/SaisirFicheFraisController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\FicheFrais;
use App\Entity\FraisForfait;
use App\Entity\LigneFraisForfait;
use App\Entity\LigneFraisHorsForfait;
use App\Form\MonthSelectorFormType;
use App\Form\SaisirFraisForfaitType;
use App\Form\SaisirFraisHorsForfaitType;
use App\Repository\EtatRepository;
use App\Repository\FicheFraisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SaisirFicheFraisController extends AbstractController
{
    #[Route('/saisirFicheFrais', name: 'app_saisir_fiche_frais')]
    public function saisirFiche(Request $request, EntityManagerInterface $entityManager, FicheFraisRepository $ficheFraisRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $today = date("Ym");
        $ficheFrais = $ficheFraisRepository->findOneBy(['user'=>$this->getUser(), 'mois'=>$today]);
        // verification si la fiche de frais du mois existe
        if ($ficheFrais == null){
            $ficheFrais = new FicheFrais();
            $ficheFrais->setUser($this->getUser());
            $ficheFrais->setMois($today);
            $ficheFrais->setDateModif(new \DateTime());
            $ficheFrais->setNbJustificatifs(0);
            $ficheFrais->setMontantValide(0);
            $etatCreation = $entityManager->getRepository(Etat::class)->find(2);
            $ficheFrais->setEtat($etatCreation);

            // création ligne frais forfaits étape
            $etape = $entityManager->getRepository(FraisForfait::class)->find(1);
            $lignesFraisForfait = new LigneFraisForfait($ficheFrais, $etape, 0);
            $ficheFrais->addLigneFraisForfait($lignesFraisForfait);

            // création ligne frais forfaits km
            $km = $entityManager->getRepository(FraisForfait::class)->find(2);
            $lignesFraisForfait = new LigneFraisForfait($ficheFrais, $km, 0);
            $ficheFrais->addLigneFraisForfait($lignesFraisForfait);

            // création ligne frais forfaits nuit
            $nuit = $entityManager->getRepository(FraisForfait::class)->find(3);
            $lignesFraisForfait = new LigneFraisForfait($ficheFrais, $nuit, 0);
            $ficheFrais->addLigneFraisForfait($lignesFraisForfait);

            // création ligne frais forfaits repas
            $repas = $entityManager->getRepository(FraisForfait::class)->find(4);
            $lignesFraisForfait = new LigneFraisForfait($ficheFrais, $repas, 0);
            $ficheFrais->addLigneFraisForfait($lignesFraisForfait);

            $entityManager->persist($ficheFrais);
            $entityManager->persist($etape);
            $entityManager->persist($km);
            $entityManager->persist($nuit);
            $entityManager->persist($repas);
            $entityManager->flush();
        }

        $formFraisForfait = $this->createForm(SaisirFraisForfaitType::class);
        $formFraisForfait->handleRequest($request);
        $toutesLesLignes = $ficheFrais->getLigneFraisForfaits();
        if (!$formFraisForfait->isSubmitted()){
            foreach ($toutesLesLignes as $ligne){
                if ($ligne->getFraisForfait()->getId() == 1){
                    $formFraisForfait->get('quantiteEtape')->setData($ligne->getQuantite());
                }
                elseif ($ligne->getFraisForfait()->getId() == 2){
                    $formFraisForfait->get('quantiteKm')->setData($ligne->getQuantite());
                }
                elseif ($ligne->getFraisForfait()->getId() == 3){
                    $formFraisForfait->get('quantiteNuit')->setData($ligne->getQuantite());
                }
                else {
                    $formFraisForfait->get('quantiteRepas')->setData($ligne->getQuantite());
                }
            }
        }

        if ($formFraisForfait->isSubmitted() && $formFraisForfait->isValid()) {
            foreach ($toutesLesLignes as $ligne){
                if ($ligne->getFraisForfait()->getId() == 1){
                    $ligne->setQuantite($formFraisForfait->get('quantiteEtape')->getData());
                }
                elseif ($ligne->getFraisForfait()->getId() == 2){
                    $ligne->setQuantite($formFraisForfait->get('quantiteKm')->getData());
                }
                elseif ($ligne->getFraisForfait()->getId() == 3){
                    $ligne->setQuantite($formFraisForfait->get('quantiteNuit')->getData());
                }
                else {
                    $ligne->setQuantite($formFraisForfait->get('quantiteRepas')->getData());
                }
            }
            $entityManager->persist($ficheFrais);
            $entityManager->flush();

            return $this->redirectToRoute('app_saisir_fiche_frais', [], Response::HTTP_SEE_OTHER);
        }

        $ligneFraisHorsForfait = new LigneFraisHorsForfait($ficheFrais, '', new \DateTime(), 0);
        $formFraisHorsForfait = $this->createForm(SaisirFraisHorsForfaitType::class, $ligneFraisHorsForfait);
        $formFraisHorsForfait->handleRequest($request);

        if ($formFraisHorsForfait->isSubmitted() && $formFraisHorsForfait->isValid()) {
            $entityManager->persist($ligneFraisHorsForfait);
            $entityManager->flush();

            return $this->redirectToRoute('app_saisir_fiche_frais', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('saisir_fiche_frais/index.html.twig', [
            'ficheFrais' => $ficheFrais,
            'formFraisForfait' => $formFraisForfait,
            'formFraisHorsForfait' => $formFraisHorsForfait,
        ]);
    }

}

templates/saisir_fiche_frais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Saisir Fiches Frais{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Renseigner ma fiche de frais du mois {{ ficheFrais.moisFormated | date('m-Y') }}</h1>
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Eléments forfaitisés</h5>
            {{ form_start(formFraisForfait) }}
            <div class="form-group">
                {{ form_row(formFraisForfait.quantiteEtape) }}
            </div>
            <div class="form-group">
                {{ form_row(formFraisForfait.quantiteKm) }}
            </div>
            <div class="form-group">
                {{ form_row(formFraisForfait.quantiteNuit) }}
            </div>
            <div class="form-group">
                {{ form_row(formFraisForfait.quantiteRepas) }}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">{{ button_label|default('Valider') }}</button>
            <button type="reset" class="btn btn-secondary">{{ button_label|default('Annuler') }}</button>
        </div>
        {{ form_end(formFraisForfait) }}
    </div>
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Descriptif des éléments hors forfait</h5>
            {{ form_start(formFraisHorsForfait) }}
            <div class="form-group">
                {{ form_row(formFraisHorsForfait.libelle) }}
            </div>
            <div class="form-group">
                {{ form_row(formFraisHorsForfait.date) }}
            </div>
            <div class="form-group">
                {{ form_row(formFraisHorsForfait.montant) }}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
        </div>
        {{ form_end(formFraisHorsForfait) }}
    </div>
    {% if ficheFrais.ligneFraisHorsForfaits.count != 0 %}
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Libellé</th>
                        <th>Date</th>
                        <th>Montant</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for fraisHF in ficheFrais.ligneFraisHorsForfaits %}
                        <tr>
                            <td>{{ fraisHF.libelle }}</td>
                            <td>{{ fraisHF.date|date('d/m/Y') }}</td>
                            <td>{{ fraisHF.montant }} €</td>
                            <td>
                                {{ include('ligne_frais_hors_forfait/_delete_form.html.twig') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}